Doctor/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Home.urls')),

] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Home/urls.py
from django.contrib import admin
from django.urls import path,include
from Home import views

from .views import(
    SpecialtiesList,
    ProceduresList,
    ConditionList,
)
app_name='Home'
urlpatterns = [
    path('',views.index,name='index'),


    #Specialties
    path('specialties/',SpecialtiesList.as_view(),name='specialties'),
    path('specialties/doctor/<int:doctor_id>/',views.specialties_doctor,name='specialties_doctor'),
    #Procedures
    path('procedures/',ProceduresList.as_view(),name='procedures'),
    path('procedures/doctor/<int:doctor_id>/',views.procedures_doctor,name='procedures_doctor'),
    #Condition
    path('condition/',ConditionList.as_view(),name='condition'),
    path('condition/doctor/<int:doctor_id>/',views.condition_doctor,name='condition_doctor'),
    
]

Home/models.py
from django.db import models
from django.contrib.auth.models import User




# Create your models here.


class Specialties(models.Model):
    name=models.CharField("mutaxasislik", max_length=100)

    def __str__(self):
        return self.name
    






class Province(models.Model):
    name=models.CharField('Viloyat', max_length=50)

    def __str__(self):
        return self.name





class District(models.Model):
    name=models.CharField('Tuman', max_length=50)
    district_id=models.ForeignKey(Province,on_delete=models.CASCADE)

    def __str__(self):
        return self.name






class Work_time(models.Model):
    name=models.CharField('ishlash kunlari', max_length=50)

    def __str__(self):
        return self.name




class Doctor(models.Model):
    name=models.CharField('Doctor ism familiya', max_length=50)
    img=models.ImageField(upload_to = 'images')
    province_id=models.ForeignKey(District, on_delete=models.CASCADE)
    address=models.CharField('address', max_length=100)

    GENDER_CHOICES=(
        ('Erkak','Erkak'),
        ('Ayol','Ayol'),
    )
    gender=models.CharField('Jinsi', max_length=5,choices=GENDER_CHOICES)
    Work_experience=(
        ('<<5','<<5'),
        ('5-10','5-10'),
        ('10-20','10-20'),
        ('20-30','20-30'),
        ('30<<','30<<')
    )
    work_experience=models.CharField('work experience', max_length=5,choices=Work_experience)
    body=models.TextField('Ummumiy malumot')
    age=models.IntegerField('Yoshi')
    specialties_id=models.ForeignKey(Specialties,on_delete=models.CASCADE)
    
    work_time_id=models.ForeignKey(Work_time, on_delete=models.CASCADE)
    phone_number=models.CharField('Raqami', max_length=9)
    date_add=models.DateField('qowilgan vaqt', auto_now=False, auto_now_add=False)
    owner=models.ForeignKey(User,on_delete=models.CASCADE)
    
    
    def __str__(self):
        return self.name




class Condition(models.Model):
    name=models.CharField('Kassalik', max_length=100)
    specialties_id=models.ForeignKey(Specialties, on_delete=models.CASCADE)
     
    def __str__(self):
        return self.name




class Procedures(models.Model):
    name=models.CharField('Operatsiya', max_length=100)
    
    specialties_id=models.ForeignKey(Specialties,on_delete=models.CASCADE)
    def __str__(self):
        return self.name



    
    

     

User/models.py
from django.db import models

# Create your models here.

Home/views.py
from django.shortcuts import render
from django.views.generic import ListView
from Home.models import Specialties,Condition,Procedures,Doctor

# Create your views here.
# Bosh sahifa
def index(request):
    return render(request,'Home/home.html')







#mutaxasislar ro'yxati
class SpecialtiesList(ListView):
    model = Specialties
    context_object_name = 'specailties'
    template_name='Home/specailties.html'





#mutaxasis bo'yicha doctorlar ro'yxati
def specialties_doctor(request,doctor_id):
    specialties=Specialties.objects.get(id=doctor_id)
    doctor=specialties.doctor_set.order_by('name')
    context={
    'specialties':specialties,
    'doctor':doctor
    
    
    }
    return render(request,'Home/specialties_doctor.html',context)



#kassaliklar ro'yxati
class ConditionList(ListView):
    model = Condition
    context_object_name = 'condition'
    template_name='Home/condition.html'




#kassalik bo'yicha doctorlar
def condition_doctor(request,doctor_id):
    condition=Condition.objects.get(id=doctor_id)
    specialties=Specialties.objects.filter(name=condition.specialties_id).get()
    doctor=specialties.doctor_set.order_by('name')
    context={
        'condition':condition,
        'specialties':specialties,
        'doctor':doctor
    }
    return render(request,'Home/condition_doctor.html',context)




#operatsiyalar ro'yxati
class ProceduresList(ListView):
    model = Procedures
    context_object_name = 'procedures'
    template_name='Home/procedures.html'


#operatsiya bo'yicha doctorlar
def procedures_doctor(request,doctor_id):
    procedures=Procedures.objects.get(id=doctor_id)
    specialties=Specialties.objects.filter(name=procedures.specialties_id).get()
    doctor=specialties.doctor_set.order_by('name')
    context={
        'procedures':procedures,
        'specialties':specialties,
        'doctor':doctor
    }
    return render(request,'Home/procecdures_doctor.html',context)

User/views.py
from django.shortcuts import render

# Create your views here.

Home/templates/Home/base.html
{% load static%}
<!doctype html>



<html lang="en">

<head>
    <title>S Doc</title> {% block title %}Welcome!{% endblock %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static  'css/style2.css' %}">
    <script src="https://kit.fontawesome.com/332a215f17.js" crossorigin="anonymous"></script>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
</head>

<body>
    {% load bootstrap4 %} {% bootstrap_css %} {% bootstrap_javascript%}
    <nav class="navbar navbar-expand-lg nav-back fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand" href="#">Medical</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><i class="fas fa-syringe fa-2x"></i>
           </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item"><a class="nav-link" href="#about">Services</a></li>
                    <li class="nav-item"><a class="nav-link" href="#about">About</a></li>
                    <li class="nav-item"><a class="nav-link" href="#about">Medical Camps</a></li>
                    <li class="nav-item"><a class="nav-link" href="#projects">Team</a></li>
                    <li class="nav-item"><a class="nav-link" href="#signup">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- End Header -->
    <div>
        <!--{% if user.is_authenticated %}
        <h1>{% block myhdg %}Hello {{ request.user.get_full_name }} {% endblock %}</h1>
        {% block body_block_1 %}
        <p><a href="/logout/ ">Logout</a></p>
        <p><a href="/myorder/ ">User's orders</a></p>
        {% endblock %} {% else %}
        <h1>{% block theBlock %}Hello Guest {% endblock %}</h1>
        {% block body_block_2 %}
        <p>You are not logged in</p>
        <a href="/login/ ">Login</a> {% endblock %} {% endif %}
    -->
    </div>
    <div style="margin:5%;  padding-left:33%;">
        <input type="text" placeholder="search a doctor "><button>Search</button>
    </div>
    {% block body_block %} {% endblock %}

    <!-- Footer-->
    <footer class="footer py-4 mt-5">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-4 text-lg-left">Copyright © Your Website 2020</div>
                <div class="col-lg-4 my-3 my-lg-0">
                    <a class="btn btn-back btn-social mx-2" href="#!">
                        <i class="fab fa-twitter"></i></a>
                    <a class="btn btn-back btn-social mx-2" href="#!">
                        <i class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-back btn-social mx-2" href="#!">
                        <i class="fab fa-linkedin-in"></i></a>
                </div>
                <div class="col-lg-4 text-lg-right">
                    <a class="mr-3 text" href="#!">Privacy Policy</a>
                    <a href="#!" class="text">Terms of Use</a></div>
            </div>
        </div>
    </footer>




















    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>

</html>

Home/templates/Home/condition.html
{% extends "Home/base.html" %}{% block body_block %}{% load static %} {% load bootstrap4%} {% for conditionss in condition%}

<div class=" card ">
    <div class="card-body ">

        <a href=" {% url 'Home:condition_doctor' conditionss.id %} " class="card-link ">{{conditionss}}</a>
    </div>
</div>
{% endfor %}{% endblock %}

Home/templates/Home/condition_doctor.html
{% extends "Home/base.html" %} {% block body_block %}{% load thumbnail %}{% load static %} {% load bootstrap4 %}{% for doctors in doctor %}


<div class="card" style="width: 18rem;   margin-top: 4%; padding: 1%;">
    <img class="card-img-top" src="{% thumbnail doctors.img 1000x5000 crop %} " width="200px;" height="100px;" alt="Card image cap ">
    <div class="card-body ">
        <h5 class="card-title ">{{doctors.name}}</h5>

        <p class="card-text ">{{doctors.ratings}}</p>
        <a href="#" class="btn btn-primary ">Go somewhere</a>
    </div>
</div>

{% endfor %}{% endblock %}

Home/templates/Home/home.html
{% extends "Home/base.html" %} {% block body_block %} {% load static %} {% load bootstrap4 %}
<div>
    <h1>


    </h1>
</div>
<div style=" padding: 1%;">
    <h1>Search taxlash kerak</h1>
</div>
<diV class="cards ">
    <div class="card ">
        <div class="card-body ">
            <h5 class="card-title ">Mutaxasislar</h5>
            <link rel="stylesheet " href="{% static 'css/home.style.css' %} ">
            <h6 class="card-subtitle mb-2 text-muted ">Card subtitle</h6>
            <p class="card-text ">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            <a href="{% url 'Home:specialties' %} " class="card-link ">Card link</a>

        </div>
    </div>
    <div class="card ">
        <div class="card-body ">
            <h5 class="card-title ">Kasaliklar</h5>
            <h6 class="card-subtitle mb-2 text-muted ">Card subtitle</h6>
            <p class="card-text ">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            <a href="{% url 'Home:condition' %} " class="card-link ">Card link</a>

        </div>
    </div>
    <div class="card ">
        <div class="card-body ">
            <h5 class="card-title ">operatsiyalar</h5>
            <h6 class="card-subtitle mb-2 text-muted ">Card subtitle</h6>
            <p class="card-text ">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            <a href="{% url 'Home:procedures' %} " class="card-link ">Card link</a>

        </div>
    </div>
</diV>
<h1>Bosh oynani nimala bilandir to'ldirish kerak masalan sayt haqida ,tavsiya etilgan doctorlar,sayt qanday iwlaw</h1>{% endblock %}

Home/templates/Home/procecdures_doctor.html
{% extends "Home/base.html" %} {% block body_block %}{% load thumbnail %}{% load static %} {% load bootstrap4 %}{% for doctors in doctor %}


<div class="card" style="width: 18rem;   margin-top: 4%; padding: 1%;">
    <img class="card-img-top" src="{% thumbnail doctors.img 1000x5000 crop %} " width="200px;" height="100px;" alt="Card image cap ">
    <div class="card-body ">
        <h5 class="card-title ">{{doctors.name}}</h5>
        <p class="card-text ">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        <a href="#" class="btn btn-primary ">Go somewhere</a>
    </div>
</div>

{% endfor %}{% endblock %}

Home/templates/Home/procedures.html
{% extends "Home/base.html" %}{% block body_block %}{% load static %} {% load bootstrap4%} {% for proceduress in procedures %}
<div class=" card ">
    <div class="card-body ">

        <a href="{% url 'Home:procedures_doctor' proceduress.id %}" class="card-link ">{{proceduress}}</a>
    </div>
</div>
{% endfor %}{% endblock %}

Home/templates/Home/specailties.html
{% extends "Home/base.html" %}{% block body_block %}{% load static %} {% load bootstrap4%} {% for specailtiess in specailties %}

<div class=" card ">
    <div class="card-body ">

        <a href="{% url 'Home:specialties_doctor' specailtiess.id %} " class="card-link ">{{specailtiess}}</a>
    </div>
</div>
{% endfor %}{% endblock %}

Home/templates/Home/specialties_doctor.html
 {% extends "Home/base.html" %} {% block body_block %}{% load thumbnail %}{% load static %} {% load bootstrap4 %}{% for doctors in doctor %}


<div class="card" style="width: 18rem;   margin-top: 4%; padding: 1%;">
    <img class="card-img-top" src="{% thumbnail doctors.img 1000x5000 crop %} " width="200px;" height="100px;" alt="Card image cap ">
    <div class="card-body ">
        <h5 class="card-title ">{{doctors.name}}</h5>
        <p class="card-text ">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        <a href="#" class="btn btn-primary ">Go somewhere</a>
    </div>
</div>

{% endfor %}{% endblock %}